# Project information
site_name: Geotribu
site_description: Veille libre sur la g√©omatique
site_author: Geotribu
site_url: https://geotribu.github.io/website/
copyright: '&#127279; geotribu'

# Repository
repo_name: 'geotribu/website'
repo_url: 'https://github.com/geotribu/website'

# advanced options
docs_dir: '../../content'
site_dir: '../../build/mkdocs/site'

# Plugins
plugins:
  - awesome-pages
  - git-revision-date-localized
  - minify:
      minify_html: true
  - search:
      prebuild_index: python

# Theme
theme:
  name: 'material'
  feature:
    tabs: true
  font: false
  language: 'fr'
  palette:
    primary: 'teal'
    accent: 'deep-orange'
  favicon: 'assets/images/geotribu/logo_geotribu.png'
  logo: 'assets/images/geotribu/logo_geotribu.png'

# Customization
extra:
  manifest: 'manifest.webmanifest'
  social:
    - type: 'github'
      link: 'https://github.com/geotribu/'
    - type: 'twitter'
      link: 'https://twitter.com/geotribu/'

# Extensions to enhance markdown - see: https://squidfunk.github.io/mkdocs-material/getting-started/#extensions
markdown_extensions:
  - admonition  # https://squidfunk.github.io/mkdocs-material/extensions/admonition/
  - codehilite: # https://squidfunk.github.io/mkdocs-material/extensions/codehilite/
      linenums: true
  - meta        # https://squidfunk.github.io/mkdocs-material/extensions/metadata/
  - toc:
      permalink: true # https://squidfunk.github.io/mkdocs-material/extensions/permalinks/

# Navigation - Menu organization
# # Disabled to use auto detection
# nav:
#   - Accueil: index.md
