icon:
  edit: material/pencil
  repo: fontawesome/brands/github-alt
  view: material/eye
  tag:
    default: fontawesome/solid/tag
    # -- custom tags icons
    3d: material/rotate-3d
    ananas: material/fruit-pineapple
    atlas: fontawesome/solid/book-atlas
    blender: material/blender-software
    brick: material/toy-brick
    carte: fontawesome/solid/map-location
    cerveau: material/brain
    citrouille: material/pumpkin
    code: fontawesome/solid/code
    commentaires: fontawesome/solid/comments
    conference: fontawesome/solid/person-chalkboard
    database: fontawesome/solid/database
    drone: material/drone
    esri: simple/esri
    facebook: fontawesome/brands/facebook
    feuille: fontawesome/solid/leaf
    gdal: simple/gdal
    gemeaux: material/zodiac-gemini
    geoloupe: fontawesome/solid/magnifying-glass-location
    git: fontawesome/brands/git-alt
    globe: fontawesome/solid/earth-europe
    google: fontawesome/brands/google
    grass: material/grass
    html: fontawesome/brands/html5
    institution: fontawesome/solid/building-columns
    js: fontawesome/brands/js
    manette: fontawesome/solid/gamepad
    mapbox: material/mapbox
    maplibre: simple/maplibre
    markdown: fontawesome/brands/markdown
    masques: fontawesome/solid/masks-theater
    mastodon: material/mastodon
    meridiens: fontawesome/solid/globe
    oeuf: fontawesome/solid/egg
    open: fontawesome/solid/lock-open
    openlayers: simple/openlayers
    opensource: material/open-source-initiative
    parquet: simple/apacheparquet
    pingouin: simple/linux
    python: fontawesome/brands/python
    qgis: simple/qgis
    qt: simple/qt
    raster: material/data-matrix
    rezosocio: material/account-network
    roue: material/cog-play
    route: fontawesome/solid/route
    rstats: fontawesome/brands/r-project
    satellite: fontawesome/solid/satellite-dish
    streetview: fontawesome/solid/street-view
    tente: material/tent
    telephone: material/cellphone-marker
    terrain: fontawesome/solid/mountain-city
    threejs: simple/threedotjs
    twitter: simple/x
    ubuntu: material/ubuntu
    vector: material/vector-polygon
    webgl: simple/webgl
    wikipedia: material/wikipedia
    windows: fontawesome/brands/windows
