name: "üé≥ Markdown Linter"

# Trigger
on:
  pull_request:
    branches: [master]
    paths:
      - ".github/workflows/pr_linter_markdown.yml"
      - "content/**/*.md"

permissions:
  contents: read
  pull-requests: write
  statuses: write

jobs:
  lint-markdown-review:
    name: "üëì V√©rification de la syntaxe"
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'geotribu' }}

    steps:
      - name: "R√©cup√®re le code source"
        uses: actions/checkout@v4

      # Filter results by added/modified lines.
      - name: "V√©rifie la syntaxe des lignes ajout√©es ou modifi√©es"
        id: markdownlint-github-pr-review-added
        uses: reviewdog/action-markdownlint@v0.26.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_error: true
          filter_mode: added
          reporter: github-pr-review

      - name: "Explications sur les erreurs du linter"
        id: pr-comment-error-create
        uses: marocchino/sticky-pull-request-comment@v2
        if: ${{ failure() && steps.markdownlint-github-pr-review-added.conclusion == 'failure' && github.event.pull_request.head.repo.fork == false }}
        with:
          header: linter-md-error
          recreate: true
          message: |
            Salut @${{ github.actor }}
            Des erreurs de syntaxe Markdown ont √©t√© d√©tect√©es dans les lignes ajout√©es ou modifi√©es. Merci de les corriger ou de les marquer comme faux-positif :

              - [r√®gles de syntaxe Markdown applicables √† Geotribu](https://contribuer.geotribu.fr/guides/markdown_quality/)
              - [marquer une erreur de syntaxe comme faux-positif](https://contribuer.geotribu.fr/internal/markdown_linter/#gerer-les-faux-positifs-du-linter)
              - [possibilit√©s de r√©daction offertes par le moteur Mkdocs + th√®me Material](https://squidfunk.github.io/mkdocs-material/reference/)

      - name: "Marque le commentaire de f√©licitations comme r√©solu"
        id: pr-comment-good-solve
        uses: marocchino/sticky-pull-request-comment@v2
        if: ${{ success() && github.event.pull_request.head.repo.fork == false }}
        with:
          header: linter-md-success
          hide: true
          hide_classify: "RESOLVED"

      # # Filter results by added/modified file. i.e. reviewdog will report results
      # # as long as they are in added/modified file even if the results are not in actual diff.
      # - name: "V√©rifie la syntaxe de tous les fichiers ajout√©s ou modifi√©s"
      #   id: markdownlint-github-pr-review-file
      #   uses: reviewdog/action-markdownlint@v0.26.0
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     fail_on_error: false
      #     filter_mode: file
      #     level: warning
      #     reporter: github-pr-review

      # SUCCESS
      - name: "Marque le commentaire d'erreur comme r√©solu"
        id: pr-comment-error-solve
        uses: marocchino/sticky-pull-request-comment@v2
        if: ${{ success() && github.event.pull_request.head.repo.fork == false }}
        with:
          header: linter-md-error
          hide: true
          hide_classify: "RESOLVED"

      - name: "F√©licitations"
        id: pr-comment-good
        uses: marocchino/sticky-pull-request-comment@v2
        if: ${{ success() && github.event.pull_request.head.repo.fork == false }}
        with:
          header: linter-md-success
          recreate: true
          message: |
            :clap: Le markdown ajout√© ou modifi√© est impeccable ! Merci :1st_place_medal:
