name: "üé≥ Markdown Linter"

# Trigger
on:
  pull_request:
    branches: [master]
    paths:
      - "content/**/*.md"

jobs:
  lint-markdown-review:
    name: "üëì V√©rification de la syntaxe"
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'geotribu' }}

    steps:
      - name: "R√©cup√®re le code source"
        uses: actions/checkout@v3

      # Filter results by added/modified lines.
      - name: "V√©rifie la syntaxe des lignes ajout√©es ou modifi√©es"
        id: markdownlint-github-pr-review-added
        uses: reviewdog/action-markdownlint@v0.7.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_error: true
          filter_mode: added
          reporter: github-pr-review

      - name: "Explications sur le linter"
        id: pr-comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: ${{ failure() && steps.markdownlint-github-pr-review-added.conclusion == 'failure' }}
        with:
          header: linter-md
          recreate: true
          message: |
            Des erreurs de syntaxe Markdown ont √©t√© d√©tect√©es. Merci de les corriger ou de les marquer comme faux-positif :
              - [r√®gles de syntaxe Markdown applicables √† Geotribu](https://static.geotribu.fr/contribuer/guides/markdown_quality/)
              - [marquer une erreur de syntaxe comme faux-positif](https://static.geotribu.fr/contribuer/guides/markdown_quality/)

      # Filter results by added/modified file. i.e. reviewdog will report results
      # as long as they are in added/modified file even if the results are not in actual diff.
      - name: "V√©rifie la syntaxe de tous les fichiers ajout√©s ou modifi√©s"
        id: markdownlint-github-pr-review-file
        uses: reviewdog/action-markdownlint@v0.7.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_error: false
          filter_mode: file
          level: warning
          reporter: github-pr-review
