name: "ðŸŽ³ Markdown Linter"

# Trigger
on:
  pull_request_target:
    branches: [master]
    paths:
      - "content/**/*.md"

jobs:
  lint-markdown-review:
    name: "ðŸ‘“ VÃ©rification de la syntaxe"
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: markdownlint-github-check
        uses: reviewdog/action-markdownlint@v0.2.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
          markdownlint_flags: 'content/**/202*/*.md'

      - name: markdownlint-github-pr-review
        uses: reviewdog/action-markdownlint@v0.2.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_error: true
          # filter_mode: diff_context
          reporter: github-pr-review
          markdownlint_flags: 'content/**/202*/*.md'
