name: "ðŸŽ³ Markdown Linter"

# Trigger
on:
  pull_request:
    branches: [master]
    paths:
      - "content/**/*.md"

jobs:
  lint-markdown-review:
    name: "ðŸ‘“ VÃ©rification de la syntaxe"
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'geotribu' }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      # - name: markdownlint-github-check
      #   uses: reviewdog/action-markdownlint@v0.5
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     filter_mode: added
      #     reporter: github-pr-check
      #     markdownlint_flags: 'content/**/202*.md'

      - name: markdownlint-github-pr-review
        uses: reviewdog/action-markdownlint@v0.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_error: true
          filter_mode: diff_context
          reporter: github-pr-review
          markdownlint_flags: "-c '.markdownlint.json' -i '**/template_*.md' 'content/**/202*.md'"
